version: 2
registries:
  rubygems-server-rubygems-pkg-github-com:
    type: rubygems-server
    url: https://rubygems.pkg.github.com
    token: "${{secrets.RUBYGEMS_SERVER_RUBYGEMS_PKG_GITHUB_COM_TOKEN}}"
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_TOKEN}}"

updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - jalyna
  ignore:
  - dependency-name: oauth2
    versions:
    - 1.4.5
    - 1.4.6
  - dependency-name: actionpack
    versions:
    - 6.1.2.1
  - dependency-name: rails
    versions:
    - 6.1.2
    - 6.1.2.1
  - dependency-name: rubocop
    versions:
    - 1.9.0
  registries:
  - rubygems-server-rubygems-pkg-github-com
- package-ecosystem: npm
  directory: "/test/dummy"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - jalyna
  registries:
  - npm-registry-npm-pkg-github-com
