inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - bin/*
    - db/**/*.rb
    - Rakefile
    - test/dummy/**/*
    - "*.gemspec"

require:
  - rubocop-performance
  - rubocop-rails

Layout/LineLength:
  Max: 119 # line length on GitHub's PR pages
  Exclude:
    - config/routes.rb

Metrics/ClassLength:
  Exclude:
    - test/**/*.rb

Metrics/MethodLength:
  Max: 15
  Exclude:
    - test/**/*.rb

Metrics/BlockLength:
  Exclude:
    - test/**/*.rb

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/AndOr:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - staging
    - sandbox
    - production

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/DateTime:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Lint/RaiseException:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
